export { easySetDoc } from './easySetDoc';
export { easyGetData, easyGetDoc, easyGetDocs } from './easyGetData';
export { easyDelDoc } from './easyDelDoc';
export { easyConnect } from './easyConnect';
export { easyUnConnect } from './easyUnConnect';
export { createRef } from './createReference';
export { isTypeCollectionOrQuery } from './helpers/checkType';
export { WhereOption, QueryOption } from '../../types/easyGetData';
export { EasySetDoc } from '../../types/easySetDoc';
export { ConnectOption } from '../../types/easyConnect';
